src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Reference;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $session;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $client;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->Reference;
    }

    public function setReference(string $Reference): self
    {
        $this->Reference = $Reference;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getSession(): ?string
    {
        return $this->session;
    }

    public function setSession(string $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getClient(): ?int
    {
        return $this->client;
    }

    public function setClient(?int $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Entity/ProductType.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * ProductType
 *
 * @ORM\Table(name="product_type")
 * @ORM\Entity(repositoryClass="App\Repository\ProductTypeRepository")
 */
class ProductType
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=150, nullable=false)
     *  @Assert\Length(
     *      min = 1,
     *      max = 100,
     *      minMessage = "El tipo de producto debe tener minimo {{ limit }} caracter.",
     *      minMessage = "El tipo de producto no puede tener una longitud mayor a {{ limit }} caracteres.",
     * )
     */
    private $name;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }



}

src/Controller/Admin/ProductController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Brand;
use App\Entity\Countries;
//use App\Entity\ProductImageAmbient;
//use App\Entity\ProductImageCover;
use App\Entity\ProductImageMin;
use App\Entity\ProductUse;
use App\Entity\Zone;
use App\Entity\Currency;
use App\Entity\Decorated;
use App\Entity\Format;
use App\Entity\Material;
use App\Entity\Product;
use App\Entity\ProductType;
use App\Entity\StockProduct;
use App\Entity\Warehouse;
use App\Repository\StockRepository;
use App\Services\GlobalManager;
use App\Services\ProductManager;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\This;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

//use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * Class ProductController
 * @package App\Controller
 * @Route ("/admin/product")
 */
class ProductController extends AbstractController

{

    private ProductManager $productManager;
    private GlobalManager $globalManager;
    private EntityManagerInterface $em;
    private ValidatorInterface $validator;
    private SluggerInterface $slugger;
    private LoggerInterface $logger;

    function __construct(ProductManager $productManager, EntityManagerInterface $em, GlobalManager $globalManager
        , ValidatorInterface $validator, SluggerInterface $slugger, LoggerInterface $logger)
    {
        $this->productManager = $productManager;
        $this->em = $em;
        $this->globalManager = $globalManager;
        $this->validator = $validator;
        $this->slugger = $slugger;
        $this->logger = $logger;
    }


    /**
     * @Route("/", name="get_all_products")
     */
    public function GetAllProducts(): Response

    {

        $products = $this->em->getRepository(Product::class)->findAll();
        $productsDTO = $this->productManager->AssingDataToDTOarray($products);
        $zone = "";
        $material = "";
        $format = "";
        $type = "";
        $types = $this->em->getRepository(ProductType::class)->findAll();
        list($zones, $materials, $formats) = $this->productManager->getZonesMaterialsAndFormats();

        return $this->render('admin/product/all.html.twig', [
            'title' => 'Productos',
            'products' => $productsDTO,
            'zones' => $zones,
            'materials' => $materials,
            'formats' => $formats,
            'types' => $types,
            'selectedZone' => $zone,
            'selectedMaterial' => $material,
            'selectedFormat' => $format,
            'selectedType' => $type,
        ]);
    }

    /**
     * @Route ("/products-filtered", name="filter_admin_products", methods={"GET"})
     */
    public function FilterProducts(Request $request)
    {
        $zone = $request->query->get('zone');
        $material = $request->query->get('material');
        $format = $request->query->get('format');
        $type = $request->query->get('type');;

        //dd($request->query->all());

        $zonelength = strlen($zone);
        $materialLength = strlen($material);
        $formatLength = strlen($format);
        $typeLength = strlen($type);
      // dd($zonelength, $materialLength, $formatLength, $typeLength);
        $products = [];

        // Filter by Zone
        if ($zonelength>0 && $materialLength<1 &&  $formatLength<1 &&  $typeLength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idZone' => $zone]);
        }

        // Filter by Material
        if ($materialLength>0 && $zonelength<1 &&  $formatLength<1 && $typeLength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idMaterial' => $material]);
        }

        // Filter by Format
        if ( $formatLength>0 && $zonelength<1 && $materialLength<1 && $typeLength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idFormat' => $format]);
        }

        // Filter by Type
        if ($typeLength>0 && $formatLength<1 && $zonelength<1 && $materialLength<1 ){
            $products = $this->em->getRepository(Product::class)->findBy(['idType' => $type]);
        }

        // Filter by Zone and Material
        if ($zonelength>0 && $materialLength>0 &&  $formatLength<1 && $typeLength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idZone' => $zone, 'idMaterial' => $material]);
        }

        // Filter by Zone and Format
        if ($zonelength>0 && $formatLength>0 && $materialLength<1 && $typeLength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idZone' => $zone, 'idFormat' => $format]);
        }

        // Filter by Zone and Type
        if ($zonelength>0 && $typeLength>0 && $formatLength<1 && $materialLength<1 ){
            $products = $this->em->getRepository(Product::class)->findBy(['idZone' => $zone, 'idType' => $type]);
        }

        // Filter by Zone, Material and Type
        if ($materialLength>0 && $typeLength>0  && $zonelength>0 && $formatLength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idZone' => $zone,'idMaterial' => $material,'idType' => $type]);
        }

        // Filter by Zone, Format and Type
        if ($zonelength>0 && $formatLength>0 &&$typeLength>0 && $materialLength<1  ){
            $products = $this->em->getRepository(Product::class)->findBy(['idZone' => $zone,'idFormat' => $format,'idType' => $type]);
        }


        // Filter by Material and Format
        if ($materialLength>0 && $formatLength>0 && $zonelength<1 && $typeLength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idMaterial' => $material, 'idFormat' => $format]);
        }

        // Filter by Material and Type
        if ($materialLength>0 && $typeLength>0 && $formatLength<1 && $zonelength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idMaterial' => $material, 'idType' => $type]);
        }

        // Filter by Material, Format and Type
        if ($materialLength>0 && $typeLength>0 && $formatLength>0 && $zonelength<1){
            $products = $this->em->getRepository(Product::class)->findBy(['idMaterial' => $material,'idFormat' => $format, 'idType' => $type]);
        }


        // Filter by Format and Type
        if ($materialLength<1 && $typeLength>0 && $formatLength>0 && $zonelength<1){
            $products = $this->em->getRepository(Product::class)->findBy([ 'idFormat' => $format, 'idType' => $type]);
        }


        // Filter by Zone, Material, Format and Type
        if ($zonelength>0 && $materialLength>0 && $formatLength>0 && $typeLength>0){
            $products = $this->em->getRepository(Product::class)
                ->findBy(['idZone' => $zone,'idMaterial' => $material, 'idFormat' => $format, 'idType' => $type]);
        }

        //Filter by All
        if ($zonelength<1 && $materialLength<1 &&  $formatLength<1 && $typeLength<1){
            return $this->redirectToRoute('get_all_products');
        }

        $productsDTO = $this->productManager->AssingDataToDTOarray($products);
        list($zones, $materials, $formats) = $this->productManager->getZonesMaterialsAndFormats();
        $types = $this->em->getRepository(ProductType::class)->findAll();
        return $this->render('admin/product/all.html.twig', [
            'title' => 'Productos',
            'products' => $productsDTO,
            'zones' => $zones,
            'materials' => $materials,
            'formats' => $formats,
            'types' => $types,
            'selectedZone' => $zone,
            'selectedMaterial' => $material,
            'selectedFormat' => $format,
            'selectedType' => $type,
        ]);
    }

    /**
     * @Route("/create", name="create_product_get", methods={"GET"})
     */
    public function CreateProductGet(): Response
    {
        $product = new Product();
        $zones = $this->em->getRepository(Zone::class)->findAll();
        $warehouses = $this->em->getRepository(Warehouse::class)->findAll();
        $productTypes = $this->em->getRepository(ProductType::class)->findAll();
        $decorated = $this->em->getRepository(Decorated::class)->findAll();
        $materials = $this->em->getRepository(Material::class)->findAll();
        $warehousesByProductId = $this->em->getRepository(StockProduct::class)->findWarehousesByProductId($product->getName());
        $formats = $this->em->getRepository(Format::class)->findAll();
        $currencies = $this->em->getRepository(Currency::class)->findAll();
        $uses = $this->em->getRepository(ProductUse::class)->findAll();
        $countries = $this->em->getRepository(Countries::class)->findAll();
        $brands = $this->em->getRepository(Brand::class)->findAll();
        return $this->render('admin/product/add.html.twig', [
            'title' => 'Crear producto',
            'product' => $product,
            'zones' => $zones,
            'warehouses' => $warehouses,
            'productTypes' => $productTypes,
            'decorated' => $decorated,
            'materials' => $materials,
            'warehousesByProduct' => $warehousesByProductId,
            'formats' => $formats,
            'currencies' => $currencies,
            'uses' => $uses,
            'countries' => $countries,
            'brands' => $brands,
        ]);
    }

    /**
     * @Route("/create", name="create_product_post", methods={"post"})
     */
    public function CreateProductPost(Request $request, SluggerInterface $slugger): Response
    {

src/Controller/Site/AgentController.php
<?php

namespace App\Controller\Site;


use App\Entity\Catalogue;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/")
 */
class AgentController extends AbstractController

{
    private EntityManagerInterface $em;
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @IsGranted ("ROLE_AGENT")
     * @Route ("profile/agent", name="public_agent_profile", methods={"GET"})
     */
    public function profile(): Response
    {
        $agentCatalogues = $this->em->getRepository(Catalogue::class)->findBy(['hasAgentVisibility' => 1]);
        return $this->render('site/profile/agent_profile.html.twig', [
            'title' => 'Zona de agentes',
            'agent_catalogues' => $agentCatalogues,
        ]);
    }






}

templates/site/product/_mobile_products_show_template.html.twig
{% set checked = '' %}
{# ---------------  Start mobile and tablet view  ---------------------#}
<div class="d-lg-none">
{#    Queda#}
    <div class="offcanvas offcanvas-start toogle-menu"  tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">

        <div class="offcanvas-body px-0 ">
            {#    Queda#}
            <form action="{{ path('filter_by') }}" method="post" id="filterForm">
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">

                    <li>
                        <span href="#" class="nav-link text-truncate text-decoration-none text-dark">
                            <i class="fs-5 bi-table"></i><span class="ms-1 font-sofia-bold">Zona</span></span>
                        {% set checked = "" %}
                        {% for zone in zones %}

                            {% if zone.id == selectedZone %}

                                {% set checked = "checked" %}
                            {% else %}
                                {% set checked = "" %}
                            {% endif %}

                 {#           {% if zone.id == 18 %}

                            {% else %}#}
                                <div class="ms-4">
                                    <div >
                                        <input type="radio" name="zone" value="{{ zone.id }}"
                                               id="{{ 'zoneMobile'~ zone.id }}"  {{ checked }} required>
                                        <label class="form-check-label" for="{{ 'zoneMobile'~ zone.id }}">
                                            {{ zone.name }}
                                        </label>
                                    </div>
                                </div>
{#                            {% endif %}#}
                        {% endfor %}

                        {% set checked = "" %}

                        {% if selectedZone == 0 %}
                            {% set checked = "checked" %}
                        {% endif %}
                        <div class="ms-4">
                            <div >
                                <input type="radio" name="zone" value="0" id="zoneMobileAll" {{ checked }}>
                                <label class="form-check-label" for="zoneMobileAll">
                                    Todos
                                </label>
                            </div>
                        </div>


                    </li>
                    {% set checked = "" %}

                    <li>
                        <span href="#" class="nav-link text-truncate">
                            <i class="fs-5 bi-grid"></i><span class="ms-1 font-sofia-bold">Acabado</span></span>
                        <div class="ms-4">
                            {% for material in materials %}

                                {% if material.id == selectedMaterials %}
                                    {% set checked = "checked" %}
                                {% endif %}

                                <div >
                                    <input  type="radio" name="material" value="{{ material.id }}" id="{{ 'materialMobile' ~ material.id }}"  {{ checked }} required>
                                    <label class="form-check-label" for="{{ 'materialMobile' ~ material.id }}">
                                        {{ material.name }}
                                    </label>
                                </div>
                                {% set checked = "" %}
                            {% endfor %}

                            {% if selectedMaterials == 0 %}
                                {% set checked = "checked" %}
                            {% endif %}
                            <div >
                                <input  type="radio" name="material" value="0" id="materialMobileAll" {{ checked }}>
                                <label class="form-check-label" for="materialMobileAll">
                                    Todos
                                </label>
                            </div>
                        </div>
                    </li>

                    <li>
                        <span href="#" class="nav-link text-truncate">
                            <i class="fs-5 bi-grid"></i><span class="ms-1 font-sofia-bold">Formato</span></span>
                        {% set checked = "" %}
                        <div class="ms-4">
                            {% if selectedFormats|length == 0 %}
                                {% set checked = "checked" %}
                            {% endif %}
                            <div >
                                <input  type="checkbox" id="allFormatsMobile"
                                       name="format" value="0" {{ checked }}>
                                <label class="form-check-label" for="allFormatsMobile">
                                    Todos
                                </label>
                            </div>

                            {% set checked = "" %}
                            <div id="formatOptionsMobile">
                                {% for format in formats %}
                                    {% for selectedFormat in selectedFormats%}
                                        {% if format.id == selectedFormat %}
                                            {% set checked = "checked" %}
                                        {% endif %}
                                    {% endfor %}
                                    <div >
                                        <input  type="checkbox" id="{{ 'formatMobile'~format.id }}"
                                               name="format[]" value="{{ format.id }}" {{ checked }}>
                                        <label class="form-check-label" for="{{ 'formatMobile'~format.id }}">
                                            {{ format.name }}
                                        </label>
                                    </div>
                                    {% set checked = "" %}
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                </ul>
            </form>
        </div>

    </div>

{#    <div class="text-center me-3">
    <span class="btn estilker-color text-white" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">
#}{#            <i class="bi bi-arrow-right-square-fill fs-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvas">btn</i>#}{#
       Filtrar
    </span>
    </div>#}

    <div class="col-10 mx-auto">
    <div class="d-grid gap-2">
         <span class="btn estilker-color text-white" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">
{#            <i class="bi bi-arrow-right-square-fill fs-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvas">btn</i>#}
       Filtrar
    </span>
    </div>
    </div>
    <div class="container ">
        <div class="col-md-10 mx-auto mt-3">
            <div class="row">
                {% for product in products %}
                    {#                {{ dump(product.imageCover) }}#}
                    <div class="col-md-5 text-center mx-auto my-auto ">
                        <div class="card model-image">
                            <a href="{{ path('site_product_show', {'id' : product.id}) }}" class="text-decoration-none text-dark">
                                <img onerror='this.src="{{ asset('product_images/image_not_found.png' ) }}"' src="{{ asset('product_images/' ~ product.imageCover ) }}"
                                     class="card-img-top" alt="ProductImage" width="100%" >
                                <div class="card-body">
                                    <h5 class="card-title">{{ product.name }}</h5>
                                    <p class="card-text">{{ product.idFormat.name }} cm</p>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <h1>Aun no tenemos productos para esta busqueda</h1>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{# ---------------  End mobile and tablet view  ---------------------#}

templates/site/product/_product_show.html.twig
{% extends 'site/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
{#    {{ dump(product) }}#}
    <div class="container">
        <div class="col-md-10 mx-auto">
            <button onClick="window.history.back();" type="button" class="btn text-estilker fs-5"  >
                <img src="{{ asset('images/arrow-back.png') }}" width="24px" alt="Volver">
                Volver
            </button>
{#            <a href=""><img src="{{ asset('images/arrow-back.png') }}" alt="Volver">Volver</a>#}
            <div class="row">
                <div class="text-center">

                        <h1 class="font-sofia-bold">{{ product.name }}</h1>
{#                    {% if product.setProduct > 1 %}     {% else %}
#}{#                        <h2>Decorados {{ product.idFormat.name }} cm</h2>#}{#

                    {% endif %}#}
                </div>

              {#  {% if product.setProduct == 1 %}
                    <h4 class="text-center">{{ product.idMaterial.name }}</h4>
                {% endif %}#}
                <div class="col-md-6">
                    <div class="text-center mt-5">
                        <img width="90%"
                             onerror='this.src="{{ asset('product_images/image_not_found.png' ) }}"' src="{{ asset('product_images/'~ product.imageCover) }}" alt="Cover image" >
                    </div>
                </div>

                <div class="col-md-4 mt-5">
                  {#  <div >
                        <h2>{{ product.name }}</h2>
                    </div>#}
                    <div class="mt-3">
                        <p><span class="font-sofia-bold">Fabricación:</span> {{ product.country.countryName }}</p>
                        <p><span class="font-sofia-bold">Formato:</span> {{ product.idFormat.name }} cm</p>
                        {% if product.setProduct > 1 %}
                            <p><span class="font-sofia-bold">Unidades: </span> {{ product.setProduct}} de 60 x 30 cm</p>
                        {% else %}
                            <p><span class="font-sofia-bold">Material:</span> {{ product.idMaterial.name }}</p>
                        {% endif %}

                        {% if product.setProduct == 1 %}
                            <p><span class="font-sofia-bold">Zona:</span> {{ product.idZone.name }}</p>
                        {% endif %}
                        <p><span class="font-sofia-bold">Marca: </span> {{ product.brand.name }}</p>
                        <p><span class="font-sofia-bold">Referencia: </span> {{ product.reference }}</p>

                    </div>
                </div>

                <div class="col-md-6 product-buttons-media-screen">
                    <div class="row mt-5">
                        <div class="col-md-6 text-end mb-2">
                        <span class="badge rounded-pill bg-white text-dark border border-dark">
                            <button class="btn btn-sm btn-link text-decoration-none" type="button" id="minus" ><i><img src="{{ asset('images/minus.png') }}" alt="Minus"></i></button>
                            <input type="text" class="btn btn-link text-dark text-decoration-none" id="quantity" name="quantity" size="1" value="1">
                             <button class="btn btn-sm btn-link text-decoration-none text-dark" type="button" id="sum" ><i><img src=" {{ asset('images/sum.png') }}" alt="Plus"></i></button>
                        </span>
                        </div>

                       {# <div class="col-md-6 text-start">
                            <button class="badge rounded-pill bg-dark text-white p-3 mb-2 fs-6" id="btnAddToCartMedium" onclick="addItemToCart({{ product.id }}, '#quantity')">Agregar</button>
                        </div>#}
                        <div class="col-md-6 text-start">
                            <button class="btn estilker-color text-white p-2 fs-6 font-sofia-bold" id="btnAddToCartMedium" onclick="addItemToCart({{ product.id }}, '#quantity')">Agregar</button>
                        </div>

                        {#<div class="col-lg-4 text-center">
                            <button class="badge rounded-pill text-white p-3 estilker-color fs-6">Finalizar pedido
                            </button>
                        </div>#}


                    </div>
                </div>
                <div class="col-md-4">

                    <div class="mt-3">
                        <ul>
                            <li>Elija <strong>agregar</strong> y todos los productos seran cotizados via
                                <strong>E-mail o WhatsApp</strong></li>
                            <li class="mt-1">Y/o consulte este producto via <strong>WhatsApp</strong></li>
                        </ul>
                    </div>
                </div>

                <div class="col-12 product-buttons-small-screen">
                    <div class="row mt-5">
                        <div class="col-sm-6 col-12 text-center mb-2">
                        <span class="badge rounded-pill bg-white text-dark border border-dark">
                            <button class="btn btn-sm btn-link text-decoration-none" type="button" id="minusMobile"><i><img src="{{ asset('images/minus.png') }}" alt="Minus"></i></button>
                            <input type="text" class="btn btn-link text-dark text-decoration-none" id="quantityMobile" name="quantityMobile" size="1" value="1">
                             <button class="btn btn-sm btn-link text-decoration-none text-dark" type="button" id="sumMobile"><i><img src=" {{ asset('images/sum.png') }}" alt="Plus"></i></button>
                        </span>
                        </div>

                        <div class="col-sm-6 col-12 text-center">
                            <button class="btn estilker-color text-white mb-2 fs-6 font-sofia-bold" id="btnAddToCartSmall" onclick="addItemToCartSmall({{ product.id }}, '#quantityMobile')">Agregar</button>
                        </div>

                        {#<div class="col-sm-6 col-12 text-center">
                            <button class="badge rounded-pill bg-dark text-white mb-2 fs-6" id="btnAddToCartSmall" onclick="addItemToCartSmall({{ product.id }}, '#quantityMobile')">Agregar</button>
                        </div>#}

                        {#<div class="col-lg-4 text-center">
                            <button class="badge rounded-pill text-white p-3 estilker-color fs-6">Finalizar pedido
                            </button>
                        </div>#}


                    </div>
                </div>


            </div>

        </div>

        </div>


{{ include('site/product/relationally_products/desktop_view.html.twig') }}

{{ include('site/product/relationally_products/mobile_view.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/app/site/productShowControl.js') }}"></script>
    <script src="{{ asset('js/app/site/addItemToCart.js') }}"></script>
    <script>
        $(document).ready(() => {
            $('.nav-bar-items a').removeClass('active-nav-page-border font-sofia-bold');
            $('#catalogue').addClass('active-nav-page-border font-sofia-bold')
        })
    </script>


{% endblock %}

templates/site/product/products_all.html.twig
{% extends 'site/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/site/publicStyles.css') }}">

{% endblock %}
{% block body %}

    <div class="container">

        {{ include('site/product/_products_show_template.html.twig') }}
        </div>

    <div class="mt-1">

    {{ include('common/_pagination.html.twig',
        {
            number_pages : number_pages,
            current_page : current_page,
        }) }}



        <span></span>

    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/app/site/productShowControl.js') }}"></script>
    <script>
        $(document).ready(() => {
            $('.nav-bar-items a').removeClass('active-nav-page-border font-sofia-bold');
            $('#catalogue').addClass('active-nav-page-border font-sofia-bold')
        })
    </script>

    <script src="{{ asset('js/app/site/sendFilterForm.js') }}"></script>


{% endblock %}