src/Entity/OrderDetail.php
<?php

namespace App\Entity;

use App\Repository\OrderDetailRepository;
use Doctrine\ORM\Mapping as ORM;
use function Symfony\Component\Translation\t;

/**
 * @ORM\Entity(repositoryClass=OrderDetailRepository::class)
 */
class OrderDetail
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $Product;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $ClientOrder;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantity;

    /**
     * @ORM\Column(name="price", type="float", nullable=true, options={"default":0})
     */
    private $price;


    public function getPrice(): ?float
    {
        return $this->price;
    }


    public function setPrice(float $price): self
    {
        $this->price = $price;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getClientOrder(): ?Order
    {
        return $this->ClientOrder;
    }

    public function setClientOrder(?Order $ClientOrder): self
    {
        $this->ClientOrder = $ClientOrder;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }
}

src/Controller/Site/AgentController.php
<?php

namespace App\Controller\Site;


use App\Entity\Catalogue;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/")
 */
class AgentController extends AbstractController

{
    private EntityManagerInterface $em;
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @IsGranted ("ROLE_AGENT")
     * @Route ("profile/agent", name="public_agent_profile", methods={"GET"})
     */
    public function profile(): Response
    {
        $agentCatalogues = $this->em->getRepository(Catalogue::class)->findBy(['hasAgentVisibility' => 1]);
        return $this->render('site/profile/agent_profile.html.twig', [
            'title' => 'Zona de agentes',
            'agent_catalogues' => $agentCatalogues,
        ]);
    }






}

src/Controller/Site/CartController.php
<?php

namespace App\Controller\Site;

use App\Controller\EncryptController;
use App\Entity\CartProductDTO;
use App\Entity\CartProductListDTO;
use App\Entity\City;
use App\Entity\Countries;
use App\Entity\CustomUser;
use App\Entity\Format;
use App\Entity\Material;
use App\Entity\Order;
use App\Entity\OrderDetail;
use App\Entity\Product;
use App\Entity\Regions;
use App\Entity\Zone;
use App\Services\GlobalManager;
use App\Services\ProductManager;
use App\Services\SessionsHandler;
use Doctrine\ORM\EntityManagerInterface;
use Nzo\UrlEncryptorBundle\Encryptor\Encryptor;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/cart")
 */
class CartController extends AbstractController

{

    private $sessionHandler;
    private $em;
    private $productManager;
    private $encrypt;

    private $globalManager;

    function __construct(SessionsHandler $sessionHandler,
                         ProductManager $productManager, EntityManagerInterface $em,
                         Encryptor $encryptor, GlobalManager $globalManager)
    {
        $this->sessionHandler = $sessionHandler;
        $this->em = $em;
        $this->productManager = $productManager;
        $this->encrypt = $encryptor;
        $this->globalManager = $globalManager;
    }

    /*
       @Route ("/test", name="test_finish_order", methods={"GET"})

     public function testFinishOrderView()
       {
           return  $this->redirectToRoute('checkout-success', ['hashedText' => $this->encrypt->encrypt(37)]);
       }*/

    /**
     * @Route ("/", name="get_cart", methods={"GET"})
     */
    public function index(): Response
    {

        $products = [];
        $productsAdded = $this->sessionHandler->getItemsInCart();
        $zones = $this->em->getRepository(Zone::class)->findAll();
        $materials = $this->em->getRepository(Material::class)->findAll();
        $formats = $this->em->getRepository(Format::class)->findAll();
        $accordionItems = $this->ProductsAccordion();
        if ($productsAdded) {
            foreach ($this->sessionHandler->getItemsInCart() as $key => $value) {
                $currentProduct = $this->em->getRepository(Product::class)->find($key);
                $products[] = $this->productManager->AssignDataToProductCartListDTO($currentProduct, $value);
            }
        }

        return $this->render('site/cart/index.html.twig', [
            'title' => 'Finalizar pedido',
            'products' => $products,
            'zones' => $zones,
            'materials' => $materials,
            'formats' => $formats,
            'accordion_items' => $accordionItems,
        ]);
    }

    /**
     * @Route ("/checkout-post", name="checkout", methods={"POST"})
     */
    public function CheckOut(Request $request): Response
    {
        if (strlen($this->sessionHandler->getSessionId()) < 1) {
            return $this->redirectToRoute('home');
        }
        $products = $this->sessionHandler->RefreshCartItemsSession($request);
        if ($products) {

            if ($oldOrder = $this->em->getRepository(Order::class)
                ->findOneBy(['session' => $this->sessionHandler->getSessionId()])) {
                $this->UpdateOrder($products, $oldOrder);
                $this->addFlash('success', 'Rellena tus datos para finalizar tu pedido!');
                return $this->redirectToRoute('checkout-get',
                    [
                        'hashedText' => $this->encrypt->encrypt($oldOrder->getId()),
                        'sessionHashed' => $this->encrypt->encrypt($this->sessionHandler->getSessionId()),
                    ]);
            } else {
                $this->addFlash('success', 'Orden creada, rellena tus datos para finalizar tu pedido!');
                return $this->redirectToRoute('checkout-get',
                    [
                        'hashedText' => $this->encrypt->encrypt($this->CreateOrder($products)->getId()),
                        'sessionHashed' => $this->encrypt->encrypt($this->sessionHandler->getSessionId()),
                    ]);

            }

        } else {
            if (strlen($this->sessionHandler->getSessionId()) > 5) {
                if ($currentOrder = $this->em->getRepository(Order::class)->findOneBy(['session' => $this->sessionHandler->getSessionId()])) {
                    if (!$currentOrder->getIsActive()) {
                        $this->em->remove($currentOrder);
                    }
                }
            }
            $this->addFlash('fail', 'Ha habido un error al procesar tu pedido, intentalo de nuevo.');
            return $this->redirectToRoute('get_cart');
        }

    }

    /**
     * @Route ("/checkout/{hashedText}/{sessionHashed}", name="checkout-get", methods={"GET"})
     */
    public function renderCheckoutView(string $hashedText, string $sessionHashed): Response
    {

        try {
            $order = $this->em->getRepository(Order::class)->find($this->encrypt->decrypt($hashedText));
            if (strcmp($order->getSession(), $this->encrypt->decrypt($sessionHashed)) != 0) {
                $this->redirectToRoute('home');
            }
        } catch (\Exception $e) {
            return $this->redirectToRoute('home');
        }
        $productsDTO = [];
        $orderDetails = $this->em->getRepository(OrderDetail::class)->findBy(['ClientOrder' => $order]);
        foreach ($orderDetails as $orderDetail) {
            $productsDTO[] = $this->productManager->AssignDataToProductCartListDTO($orderDetail->getProduct(), $orderDetail->getQuantity());

        }

        $regions = $this->em->getRepository(Regions::class)->findAll();
        return $this->render('site/cart/checkout.html.twig', [
            'title' => 'Datos facturacion',
            'products' => $productsDTO,
            'order' => $order->getId(),
            'regions' => $regions,

        ]);

    }

    /**
     * @Route ("/finish-order", name="finish_order", methods={"POST"})
     */
    public function FinishOrder(Request $request): \Symfony\Component\HttpFoundation\RedirectResponse
    {
        $order = $this->em->getRepository(Order::class)->find($request->request->get('orderId'));
        if ($order) {
            //$customUser = $this->AssignDataToNewCustomUser($request);
            if ($existingEmail = $this->em->getRepository(CustomUser::class)->findOneBy(['email' => trim($request->request->get('email'))])){
               $customUser = $this->AssignDataToExistingCustomUser($existingEmail,$request);
            } else {
                $customUser = $this->AssignDataToNewCustomUser($request);
            }

            if ($this->globalManager->CheckErrorsOnValidation($this->globalManager->ValidatorCustomUser($customUser))) {
                return $this->redirectToRoute('get_cart');
            }
            $this->em->persist($customUser);
            $this->em->flush();
            $order->setClient($customUser->getId())
                ->setIsActive(true);
            $orderReference = $order->getId() . '-' . substr($customUser->getName(), 0, 2) .
                substr($customUser->getSurname(), 0, 2) . '-' . date_format($order->getCreatedAt(), "d/m/Y");
            $order->setReference($orderReference);
            $this->em->persist($order);
            $this->em->flush();

            $this->sessionHandler->invalidateSession();
            $this->addFlash('success', 'Pedido realizado, pronto contactaremos contigo');
            return  $this->redirectToRoute('checkout-success', ['hashedText' => $this->encrypt->encrypt($order->getId())]);
            //return $this->redirectToRoute('home');


        }
        $this->addFlash('fail', 'Ha ocurrido un error localizando tu orden, intentalo en unos minutos.');
        return $this->redirectToRoute('home');

    }

    /**
     * @Route ("/checkout-success/{hashedText}", name="checkout-success", methods={"GET"})
     */
    public function CheckOutSuccess(string $hashedText)
    {
        $order = $this->em->getRepository(Order::class)->find($this->encrypt->decrypt($hashedText));
        if ($order){
            return $this->render('site/cart/checkout_success.html.twig', [
                'title' => 'Pedido realizado',
                'order_number' => $order->getId(),
                'hashedText' => $this->encrypt->encrypt($order->getId()),
            ]);
        }

        $this->addFlash('fail', 'Ha ocurrido un error localizando tu orden, intentalo en unos minutos. Disculpa las molestias.');
        return $this->redirectToRoute('home');

    }
    /**
     * @Route("/cities/{id<\d+>}", name="public_get_cities_json", methods={"GET"})
     */
    public function getCities(int $id): Response
    {

        $region = $this->em->getRepository(Regions::class)->find($id);
        $cities = $this->em->getRepository(City::class)->findByRegionId($region->getId());

        return new JsonResponse($cities);
    }

    /**
     * @Route ("/add", name="add_cart_item", methods={"POST"})
     */
    public function addItemToCart(Request $request): JsonResponse
    {

        $numberItems = $this->sessionHandler->addItemToSession($request);
        if ($numberItems) {
            return new JsonResponse($numberItems, 201);
        } else {
            return new JsonResponse('', 404);
        }

    }

    /**
     * @Route ("/add-from-Cart", name="add_cart_item_from_cart", methods={"POST"})
     */
    public function addItemToCartFromCartView(Request $request): RedirectResponse
    {
        //dd($request->request->all());
      //  dd($this->sessionHandler->addItemToSession($request));
        if($this->sessionHandler->addItemToSessionFromCartView($request) != null){

templates/site/cart/checkout.html.twig
{% extends 'site/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/site/publicStyles.css') }}">
{% endblock %}

{% block body %}

<div class="container">
    <div class="col-md-12">
        <div class="row">
        <div class="col-md-6">
            <form action="{{ path('finish_order') }}" method="post" id="checkoutForm">
                <input type="hidden" name="orderId" id="orderId" value="{{ order }}">
                <div class="row">
                    <h1 class="font-sofia-bold">Detalles de facturación</h1>
                    <div class="col">
                        <label for="name">Nombre <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Ejemplo: Juan">
                        <span class="helperName"></span>
                    </div>
                    <div class="col">
                        <label for="surname">Apellidos <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="surname" name="surname" placeholder="Ejemplo: Perez">
                        <span class="helperSurname"></span>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col">
                        <label for="phone">Telefono <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="phone" id="phone" placeholder="0006521" pattern="[0-9]+">
                        <span class="helperPhone"></span>
                    </div>

                    <div class="col">
                        <label for="email">Email <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="email" id="email" placeholder="ejemplo@ej.es">
                        <span class="helperEmail"></span>
                    </div>

                </div>
                <div class="row mt-3">

                    <div class="col">
                        <label for="region">Region <span class="text-danger">*</span></label>
                        <select class="form-select" name="region" id="region" aria-label="Default select example" required>
                            <option selected value="" class="text-center">-- Departamento --</option>
                             {% for region in regions %}
                            <option value="{{ region.id }}">{{ region.name }}</option>
                            {% endfor %}
                        </select>
                        <span class="helperRegion"></span>

                    </div>
                    <div class="col">
                        <label for="city">Ciudad <span class="text-danger">*</span></label>
                        <select class="form-select" name="city" id="city" aria-label="Default select example" required>
                            <option value="" selected>-- Selecciona un departamento --</option>
                        </select>

                        <span class="helperCity"></span>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col">
                        <label for="additionalInfo" class="text-start">Informacion adicional: </label>
                        <textarea class="form-control" name="additionalInfo" id="additionalInfo" rows="5"
                                  cols="20"
                                  placeholder="Informacion adicional"></textarea>
                        <span class="helperInfo"></span>
                    </div>

                </div>

                {#<div class="row mt-3">
                    <div class="form-check ms-3">
                        <input class="form-check-input" type="checkbox"  id="checkBox" name="checkBox">
                        <label class="form-check-label" for="flexCheckDefault">
                            Declaro leídas y aceptadas las condiciones de <a href="#">Aviso legal y Política de
                                privacidad.</a>
                        </label>
                        <span class="helperCheck"></span>
                    </div>
                </div>#}



            <div class="d-grid gap-2 mt-3 ms-5 me-5">
                <button class="btn estilker-color text-white font-sofia-regular fs-5" id="checkoutFormBtn" type="button">Finalizar pedido</button>
            </div>
            </form>
        </div>

        <div class="col-md-6">
            <div class="p-5 mx-auto">
                <div class="checkout-style p-3">
                <h2 class="text-center">Resumen de tu pedido</h2>
                    <hr class="custom-border-checkout">
                    {% set total = 0 %}
                {% for product in products %}
                    {% set total = total + product.quantity %}
                    <div class="col-md-12 ps-2 pe-2" id="{{ 'div' ~ product.id }}">
                        <div class="shadow p-3 mb-5">
                            <div class="row">
                                <div class="col-4 my-auto">
                                    <img class="rounded"
                                         onerror='this.src="{{ asset('product_images/image_not_found.png' ) }}"' src="{{ asset('product_images/' ~ product.image) }}"
                                         width="90%"
                                         alt="Product Image">
                                    </div>

                                <div class="col-4  mt-3 text-center">
                                    <p>{{ product.name }}</p>
                                </div>

                                <div class="col-4  mt-3 text-end">
                                    <p>X {{ product.quantity }}</p>

                                </div>
                                {% if product.price > 0 %}
                                    <hr>
                                    <div class="col-6">
                                        <p class="text-danger text-end font-sofia-bold">¡OUTLET!</p>
                                    </div>
                                <div class="col-6 text-end">
                                    <p class="font-sofia-bold">Precio: <span class="text-danger">{{ product.price }} $</span></p>
                                </div>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                    <hr class="custom-border-checkout">

                    {% endfor %}
                   {# <div class="row">
                        <div class="col-md-10 text-end">
                            <span class="fs-3">Total</span>
                        </div>
                        <div class="col-md-2 text-start">
                            <span class="fs-3">5</span>
                        </div>
                    </div>#}
                    <div class="ms-2 me-4">
                    <div class="d-flex justify-content-end">
                        <h4>Total unidades: {{ total }}</h4>
                    </div>
                    </div>
                    {#<div class="col-md-12 ps-2 pe-3 text-end">
                        <h3>Total: <span class="ms-5">5</span></h3>
                    </div>#}
                </div>
            </div>
        </div>
    </div>
        {#<div class="text-center mt-4">
            <button class="btn estilker-color text-white font-sofia-regular fs-5 w-50" type="button">Finalizar pedido</button>
            #}{#                    <button class="btn btn-primary" type="button">Button</button>#}{#
        </div>#}
    </div>
</div>

{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/app/site/deleteItemFromCart.js') }}"></script>
    <script src="{{ asset('js/app/site/productQuantityCartControl.js') }}"></script>
    <script src="{{ asset('js/app/site/jquery_numeric.js') }}"></script>
    <script src="{{ asset('js/app/site/checkoutForm.js') }}"></script>


{% endblock %}

templates/site/cart/checkout_success.html.twig
{% extends 'site/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/site/publicStyles.css') }}">
{% endblock %}

{% block body %}

<div class="container">
    <input type="hidden" value="{{ hashedText }}" name="pdf">
    <div class="col-8 mx-auto">
        <div class="text-center mb-5"><img src="{{ asset('images/cart_success_order.png') }}" alt=""></div>
{#      {{ render(controller('App\\Controller\\PdfMakerController::pdfMaker', { 'hashedText' : hashedText})) }}#}
        <h1 class="text-center font-sofia-bold">¡Pedido #{{ order_number }} realizado con exito!</h1>
        <h2 class="text-justify">Gracias por realizar su pedido con nosotros. En breve nuestros comerciales se pondran en contacto con usted.</h2>
        <div class="row">
            <div class="col-md-6 mt-3 text-center text-md-end">
                <a href="{{ path('pdf_maker', {'hashedText' : hashedText }) }}"
                   class="btn fs-6 font-sofia-bold generate download-catalogue-sucess" id="generate">
                    {#            <img class="me-2" src="{{ asset('images/download-cloud.png') }}" alt="Descarga">#}
                    <i class="icon-file-pdf me-2"></i>Genera tu PDF aquí
                </a>
            </div>

            <div class="col-md-6 mt-3 text-center text-md-start">
                <a href="{{ path('catalogue') }}"  class="btn fs-6 font-sofia-bold" id="see-more">Sigue viendo productos</a>
            </div>
        </div>
        <h2 class="text-center mt-5">También puedes contactarnos por WhatsApp o Email</h2>
        <div class="row mt-3">
            <div class="col-md-6 text-center text-md-end" >
                <button class="btn fs-6 font-sofia-bold estilker-border">
                    <a
                            href="https://api.whatsapp.com/send?phone=573156122776&text=Hola!%20Quiero%20consultar%20el%20estado%20de%20mi%20pedido%20numero%20{{ nzo_decrypt(hashedText) }}%20."
                            target="_blank"
                            class="text-decoration-none text-dark">
                        <i class="me-2"><img src="{{ asset('images/logos/whatsapp.png') }}" alt="WhatsApp"
                                             id="whatsapp"></i>WHATSAPP
                    </a>
                </button>

            </div>

            <div class="col-md-6 text-center text-md-start">
                <button class="btn fs-6 font-sofia-bold estilker-border">
                <a href="mailto:servicioalcliente@estilkercolombia.co?subject=Hola! Quiero consultar el estado de mi pedido numero {{ nzo_decrypt(hashedText) }}."
                  class="text-decoration-none text-dark" >
                        <i class="me-2"><img src="{{ asset('images/logos/rrss/cart_icon_mail.png') }}" width="42" alt="Email"></i>
                        MAIL
                </a>
                </button>
            </div>
        </div>
       {# <h3>Genera tu PDF pinchando <a id="generate" href="{{ path('pdf_maker', {'hashedText' : hashedText }) }}">aquí</a></h3>
        <h3><a href="{{ path('catalogue') }}">Sigue viendo más productos.</a></h3>#}
{#        <a class="text-decoration-none " href="{{ path('pdf_maker', {'hashedText' : hashedText }) }}">#{{ order_number }}</a>#}
    </div>


</div>

{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script>

        $(document).ready(()=>{
             document.getElementById('generate').click();
        })
    </script>
{#    <script src="{{ asset('js/app/site/deleteItemFromCart.js') }}"></script>
    <script src="{{ asset('js/app/site/productQuantityCartControl.js') }}"></script>
    <script src="{{ asset('js/app/site/jquery_numeric.js') }}"></script>
    <script src="{{ asset('js/app/site/checkoutForm.js') }}"></script>#}


{% endblock %}

templates/site/cart/email_template.html.twig
{% extends 'site/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="container">

    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script>

    </script>


{% endblock %}